server:
  port: 80
  max-http-header-size: 10240

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
#  profiles:
#    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.141.209.224:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: sdzh521

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations:
    - classpath*:cn/stylefeng/guns/**/mapping/*.xml

log:
  path: _app_logs